trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Echo message
- script: echo "🚀 Azure Pipeline is running!"
  displayName: 'Echo Message'

# Step 2: Maven build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
