trigger:
- main

# Use your self-hosted agent pool
pool:
  name: default

steps:
# ✅ Set JAVA_HOME manually if JDK 11 is already installed on the self-hosted agent

# ✅ Maven build step
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'  # Uses the manually set JAVA_HOME
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

