- name: Deploy artifact
  hosts: localhost
  become: true  # If you need sudo/root access
  tasks:
    - name: Ensure the deployment directory exists
      file:
        path: /opt/deploy1
        state: directory
        mode: '0755'

    - name: Copy the artifact to the deployment directory
      copy:
        src: /var/lib/jenkins/mvn4/workspace/target/MyMavenApp-1.0-SNAPSHOT.jar  # Replace with actual file
        dest: /opt/deploy1/vikas.jar

